const haishinchuuData = [
    {
        "airDate": '2026-03-16',
        "subDate": '2026-03-18',
        "engTitle": 'Documentary of 41stSG Under Live ~A different view from the 6th generation~ Part 3',
        "japTitle": 'Documentary of 41stSG アンダーライブ～6期生と違う景色～最終回',
        "linkVideo": 'https://www.youtube.com/watch?v=azvnQ4b4xbU',
        "linkSubs": 'https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20260316_41st_single_documentary_p3/41st_doc_p3.srt',
    },
    {
        "airDate": '2026-03-10',
        "subDate": '2026-03-11',
        "engTitle": 'Documentary of 41stSG Under Live ~A different view from the 6th generation~ Part 2',
        "japTitle": 'Documentary of 41stSG アンダーライブ～6期生と違う景色～第2回',
        "linkVideo": 'https://www.youtube.com/watch?v=mvphuDcX_pk',
        "linkSubs": 'https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20260310_41st_single_documentary_p2/41st_doc_p2.srt',
    },
    {
        "airDate": '2026-03-04',
        "subDate": '2026-03-06',
        "engTitle": 'Documentary of 41stSG Under Live ~A Different View from the 6th Generation~ Teaser Edition',
        "japTitle": 'Documentary of 41stSG アンダーライブ～6期生と違う景色～ティザー編',
        "linkVideo": 'https://www.youtube.com/watch?v=Nj7Gu0yeYmE',
        "linkSubs": 'https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20260304_41st_single_documentary_p1/41st_doc_p1.srt',
    },
	{
        "airDate": '2025-09-13',
        "subDate": '2025-09-18',
        "engTitle": '[Behind the Scenes] Ichinose was filming the entire Tokyo performance of the Midsummer National Tour 2025 ♪ [Meiji Jingu Baseball Stadium]',
        "japTitle": '【ライブ裏側】真夏の全国ツアー2025 東京公演で一ノ瀬がずっとカメラ回してくれました♪【明治神宮野球場】',
        "linkVideo": 'https://www.youtube.com/watch?v=uDTVynKuuYc',
        "linkSubs": 'https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20250917_ichinose_tour_jingu/ichinose_jingu.srt',
    },
    {
        "airDate": '2025-08-15',
        "subDate": '2025-09-14',
        "engTitle": "[Please enjoy it as much as we do!] Midsummer National Tour 2025 PR Strategy! Kagawa Edition [Kagawa performances start tomorrow🎤]",
        "japTitle": '【同じように楽しんでみてください♪】真夏の全国ツアー2025PR大作戦！香川篇【明日からは香川公演🎤】',
        "linkVideo": 'https://www.youtube.com/watch?v=QX8ucln_zTI',
        "linkSubs": 'https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20250815_kagawa_kaki_urumi_nagi/kagawa_kaki_urumi_nagi.srt',
    },
    {
        "airDate": '2025-08-29',
        "subDate": '2025-09-01',
        "engTitle": "[For the first time in their lives!] Masuda Mirine and Yada Moeka visit the coveted Harajuku! [Mirine's quotes are all revealed! A new nickname too?!]",
        "japTitle": '【人生初！】増田三莉音と矢田萌華が憧れの原宿にいってみた！【三莉音語録全開！新しいあだ名も？！',
        "linkVideo": 'https://www.youtube.com/watch?v=ZmA_GnoNv20',
        "linkSubs": 'https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20250830_masuda_yada_harajuku/masuda_yada_harajuku.srt',
    },
    {
        "airDate": '2025-07-14',
        "subDate": "2025-08-30",
        "engTitle": "[Eat to your heart's content in Osaka🍴] Midsummer National Tour 2025 PR Strategy! Osaka Edition [Osaka performances start on Wednesday, July 16th🐙]",
        "japTitle": "【大阪で食い倒れ🍴】真夏の全国ツアー2025PR大作戦！大阪篇【7/16(水)からは大阪公演スタート🐙】",
        "linkVideo": "https://www.youtube.com/watch?v=eFj1mVoU1Nw",
        "linkSubs": "https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20250818_osaka_summer_2025/osaka_summer2025.srt",
    },
    {
        "airDate": '2025-08-01',
        "subDate": "2025-08-19",
        "engTitle": "[Shinkansen Announcement] Midsummer National Tour 2025 PR Strategy! Miyagi Edition [Miyagi performances tomorrow and the day after tomorrow 🎤]",
        "japTitle": "【新幹線アナウンス】真夏の全国ツアー2025PR大作戦！宮城篇【明日明後日は宮城公演🎤】",
        "linkVideo": "https://www.youtube.com/watch?v=BpJbbTk_dQk",
        "linkSubs": "https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20250819_miyagi_summer_2025/miyagi_summer_2025.srt",
    },
    {
        "airDate": "2025-08-08",
        "subDate": "2025-08-14",
        "engTitle": "[Eat-To-Drop Trip] Midsummer National Tour 2025 PR Strategy! Fukuoka Edition [Tomorrow and the day after tomorrow are Fukuoka performances🎤]",
        "japTitle": "【食い倒れ旅】真夏の全国ツアー2025PR大作戦！福岡篇【明日明後日は福岡公演🎤】",
        "linkVideo": "https://www.youtube.com/watch?v=NgoPNUyLTpQ",
        "linkSubs": "https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20250814_fukuoka_summer_2025/fukuoka_sumer_2025.srt",
    },
    {
        "airDate": "2025-03-18",
        "subDate": "2025-08-12",
        "engTitle": "[Thai Food] Iroha's Munching World Travel ✈️ [Photography and Editing by Iroha Okuda]",
        "japTitle": "【タイ料理】いろはのもぐもぐ世界旅行✈️【撮影・編集 奥田いろは】",
        "linkVideo": "https://www.youtube.com/watch?v=7D_K982N__0",
        "linkSubs": "https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20250812_iroha_thai/iroha.srt",
    },
    {
        "airDate": "2025-03-11",
        "subDate": "2025-08-10",
        "engTitle": "[Real] Aruno Nakanishi eats breakfast at Matsuya",
        "japTitle": "【リアル】中西アルノ、松屋で朝ごはんを食べる",
        "linkVideo": "https://www.youtube.com/watch?v=N3at1wgMI8Y",
        "linkSubs": "https://github.com/nevepura/nogisubs2/blob/main/haishinchuu/20250810_aruno_matsuya/aruno_eat_medium_eng.srt",
    },


]